/*
 * Generated by dtrace(1M).
 */

#ifndef	_EDITLINETEST_H
#define	_EDITLINETEST_H

#if !defined(DTRACE_PROBES_DISABLED) || !DTRACE_PROBES_DISABLED
#include <unistd.h>

#endif /* !defined(DTRACE_PROBES_DISABLED) || !DTRACE_PROBES_DISABLED */

#ifdef	__cplusplus
extern "C" {
#endif

#define EDITLINETEST_STABILITY "___dtrace_stability$EditlineTest$v1$1_1_0_1_1_0_1_1_0_1_1_0_1_1_0"

#define EDITLINETEST_TYPEDEFS "___dtrace_typedefs$EditlineTest$v2"

#if !defined(DTRACE_PROBES_DISABLED) || !DTRACE_PROBES_DISABLED

#define	EDITLINETEST_TEST_MULTILINE_ENTRY(arg0) \
do { \
	__asm__ volatile(".reference " EDITLINETEST_TYPEDEFS); \
	__dtrace_probe$EditlineTest$test__multiline__entry$v1$63686172202a(arg0); \
	__asm__ volatile(".reference " EDITLINETEST_STABILITY); \
} while (0)
#define	EDITLINETEST_TEST_MULTILINE_ENTRY_ENABLED() \
	({ int _r = __dtrace_isenabled$EditlineTest$test__multiline__entry$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	EDITLINETEST_TEST_MULTILINE_RETURN(arg0) \
do { \
	__asm__ volatile(".reference " EDITLINETEST_TYPEDEFS); \
	__dtrace_probe$EditlineTest$test__multiline__return$v1$63686172202a(arg0); \
	__asm__ volatile(".reference " EDITLINETEST_STABILITY); \
} while (0)
#define	EDITLINETEST_TEST_MULTILINE_RETURN_ENABLED() \
	({ int _r = __dtrace_isenabled$EditlineTest$test__multiline__return$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	EDITLINETEST_TEST_SINGLELINE_ENTRY() \
do { \
	__asm__ volatile(".reference " EDITLINETEST_TYPEDEFS); \
	__dtrace_probe$EditlineTest$test__singleline__entry$v1(); \
	__asm__ volatile(".reference " EDITLINETEST_STABILITY); \
} while (0)
#define	EDITLINETEST_TEST_SINGLELINE_ENTRY_ENABLED() \
	({ int _r = __dtrace_isenabled$EditlineTest$test__singleline__entry$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	EDITLINETEST_TEST_SINGLELINE_RETURN() \
do { \
	__asm__ volatile(".reference " EDITLINETEST_TYPEDEFS); \
	__dtrace_probe$EditlineTest$test__singleline__return$v1(); \
	__asm__ volatile(".reference " EDITLINETEST_STABILITY); \
} while (0)
#define	EDITLINETEST_TEST_SINGLELINE_RETURN_ENABLED() \
	({ int _r = __dtrace_isenabled$EditlineTest$test__singleline__return$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	EDITLINETEST_TESTCASE_SETUP_ENTRY() \
do { \
	__asm__ volatile(".reference " EDITLINETEST_TYPEDEFS); \
	__dtrace_probe$EditlineTest$testcase__setup__entry$v1(); \
	__asm__ volatile(".reference " EDITLINETEST_STABILITY); \
} while (0)
#define	EDITLINETEST_TESTCASE_SETUP_ENTRY_ENABLED() \
	({ int _r = __dtrace_isenabled$EditlineTest$testcase__setup__entry$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	EDITLINETEST_TESTCASE_SETUP_RETURN() \
do { \
	__asm__ volatile(".reference " EDITLINETEST_TYPEDEFS); \
	__dtrace_probe$EditlineTest$testcase__setup__return$v1(); \
	__asm__ volatile(".reference " EDITLINETEST_STABILITY); \
} while (0)
#define	EDITLINETEST_TESTCASE_SETUP_RETURN_ENABLED() \
	({ int _r = __dtrace_isenabled$EditlineTest$testcase__setup__return$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	EDITLINETEST_TESTCASE_TEARDOWN_ENTRY() \
do { \
	__asm__ volatile(".reference " EDITLINETEST_TYPEDEFS); \
	__dtrace_probe$EditlineTest$testcase__teardown__entry$v1(); \
	__asm__ volatile(".reference " EDITLINETEST_STABILITY); \
} while (0)
#define	EDITLINETEST_TESTCASE_TEARDOWN_ENTRY_ENABLED() \
	({ int _r = __dtrace_isenabled$EditlineTest$testcase__teardown__entry$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	EDITLINETEST_TESTCASE_TEARDOWN_RETURN() \
do { \
	__asm__ volatile(".reference " EDITLINETEST_TYPEDEFS); \
	__dtrace_probe$EditlineTest$testcase__teardown__return$v1(); \
	__asm__ volatile(".reference " EDITLINETEST_STABILITY); \
} while (0)
#define	EDITLINETEST_TESTCASE_TEARDOWN_RETURN_ENABLED() \
	({ int _r = __dtrace_isenabled$EditlineTest$testcase__teardown__return$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	EDITLINETEST_TESTSUITE_SETUP_ENTRY() \
do { \
	__asm__ volatile(".reference " EDITLINETEST_TYPEDEFS); \
	__dtrace_probe$EditlineTest$testsuite__setup__entry$v1(); \
	__asm__ volatile(".reference " EDITLINETEST_STABILITY); \
} while (0)
#define	EDITLINETEST_TESTSUITE_SETUP_ENTRY_ENABLED() \
	({ int _r = __dtrace_isenabled$EditlineTest$testsuite__setup__entry$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	EDITLINETEST_TESTSUITE_SETUP_RETURN() \
do { \
	__asm__ volatile(".reference " EDITLINETEST_TYPEDEFS); \
	__dtrace_probe$EditlineTest$testsuite__setup__return$v1(); \
	__asm__ volatile(".reference " EDITLINETEST_STABILITY); \
} while (0)
#define	EDITLINETEST_TESTSUITE_SETUP_RETURN_ENABLED() \
	({ int _r = __dtrace_isenabled$EditlineTest$testsuite__setup__return$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	EDITLINETEST_TESTSUITE_TEARDOWN_ENTRY() \
do { \
	__asm__ volatile(".reference " EDITLINETEST_TYPEDEFS); \
	__dtrace_probe$EditlineTest$testsuite__teardown__entry$v1(); \
	__asm__ volatile(".reference " EDITLINETEST_STABILITY); \
} while (0)
#define	EDITLINETEST_TESTSUITE_TEARDOWN_ENTRY_ENABLED() \
	({ int _r = __dtrace_isenabled$EditlineTest$testsuite__teardown__entry$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	EDITLINETEST_TESTSUITE_TEARDOWN_RETURN() \
do { \
	__asm__ volatile(".reference " EDITLINETEST_TYPEDEFS); \
	__dtrace_probe$EditlineTest$testsuite__teardown__return$v1(); \
	__asm__ volatile(".reference " EDITLINETEST_STABILITY); \
} while (0)
#define	EDITLINETEST_TESTSUITE_TEARDOWN_RETURN_ENABLED() \
	({ int _r = __dtrace_isenabled$EditlineTest$testsuite__teardown__return$v1(); \
		__asm__ volatile(""); \
		_r; })


extern void __dtrace_probe$EditlineTest$test__multiline__entry$v1$63686172202a(const char *);
extern int __dtrace_isenabled$EditlineTest$test__multiline__entry$v1(void);
extern void __dtrace_probe$EditlineTest$test__multiline__return$v1$63686172202a(const char *);
extern int __dtrace_isenabled$EditlineTest$test__multiline__return$v1(void);
extern void __dtrace_probe$EditlineTest$test__singleline__entry$v1(void);
extern int __dtrace_isenabled$EditlineTest$test__singleline__entry$v1(void);
extern void __dtrace_probe$EditlineTest$test__singleline__return$v1(void);
extern int __dtrace_isenabled$EditlineTest$test__singleline__return$v1(void);
extern void __dtrace_probe$EditlineTest$testcase__setup__entry$v1(void);
extern int __dtrace_isenabled$EditlineTest$testcase__setup__entry$v1(void);
extern void __dtrace_probe$EditlineTest$testcase__setup__return$v1(void);
extern int __dtrace_isenabled$EditlineTest$testcase__setup__return$v1(void);
extern void __dtrace_probe$EditlineTest$testcase__teardown__entry$v1(void);
extern int __dtrace_isenabled$EditlineTest$testcase__teardown__entry$v1(void);
extern void __dtrace_probe$EditlineTest$testcase__teardown__return$v1(void);
extern int __dtrace_isenabled$EditlineTest$testcase__teardown__return$v1(void);
extern void __dtrace_probe$EditlineTest$testsuite__setup__entry$v1(void);
extern int __dtrace_isenabled$EditlineTest$testsuite__setup__entry$v1(void);
extern void __dtrace_probe$EditlineTest$testsuite__setup__return$v1(void);
extern int __dtrace_isenabled$EditlineTest$testsuite__setup__return$v1(void);
extern void __dtrace_probe$EditlineTest$testsuite__teardown__entry$v1(void);
extern int __dtrace_isenabled$EditlineTest$testsuite__teardown__entry$v1(void);
extern void __dtrace_probe$EditlineTest$testsuite__teardown__return$v1(void);
extern int __dtrace_isenabled$EditlineTest$testsuite__teardown__return$v1(void);

#else

#define	EDITLINETEST_TEST_MULTILINE_ENTRY(arg0) \
do { \
	} while (0)
#define	EDITLINETEST_TEST_MULTILINE_ENTRY_ENABLED() (0)
#define	EDITLINETEST_TEST_MULTILINE_RETURN(arg0) \
do { \
	} while (0)
#define	EDITLINETEST_TEST_MULTILINE_RETURN_ENABLED() (0)
#define	EDITLINETEST_TEST_SINGLELINE_ENTRY() \
do { \
	} while (0)
#define	EDITLINETEST_TEST_SINGLELINE_ENTRY_ENABLED() (0)
#define	EDITLINETEST_TEST_SINGLELINE_RETURN() \
do { \
	} while (0)
#define	EDITLINETEST_TEST_SINGLELINE_RETURN_ENABLED() (0)
#define	EDITLINETEST_TESTCASE_SETUP_ENTRY() \
do { \
	} while (0)
#define	EDITLINETEST_TESTCASE_SETUP_ENTRY_ENABLED() (0)
#define	EDITLINETEST_TESTCASE_SETUP_RETURN() \
do { \
	} while (0)
#define	EDITLINETEST_TESTCASE_SETUP_RETURN_ENABLED() (0)
#define	EDITLINETEST_TESTCASE_TEARDOWN_ENTRY() \
do { \
	} while (0)
#define	EDITLINETEST_TESTCASE_TEARDOWN_ENTRY_ENABLED() (0)
#define	EDITLINETEST_TESTCASE_TEARDOWN_RETURN() \
do { \
	} while (0)
#define	EDITLINETEST_TESTCASE_TEARDOWN_RETURN_ENABLED() (0)
#define	EDITLINETEST_TESTSUITE_SETUP_ENTRY() \
do { \
	} while (0)
#define	EDITLINETEST_TESTSUITE_SETUP_ENTRY_ENABLED() (0)
#define	EDITLINETEST_TESTSUITE_SETUP_RETURN() \
do { \
	} while (0)
#define	EDITLINETEST_TESTSUITE_SETUP_RETURN_ENABLED() (0)
#define	EDITLINETEST_TESTSUITE_TEARDOWN_ENTRY() \
do { \
	} while (0)
#define	EDITLINETEST_TESTSUITE_TEARDOWN_ENTRY_ENABLED() (0)
#define	EDITLINETEST_TESTSUITE_TEARDOWN_RETURN() \
do { \
	} while (0)
#define	EDITLINETEST_TESTSUITE_TEARDOWN_RETURN_ENABLED() (0)

#endif /* !defined(DTRACE_PROBES_DISABLED) || !DTRACE_PROBES_DISABLED */


#ifdef	__cplusplus
}
#endif

#endif	/* _EDITLINETEST_H */
